version: '3.8'

services:
  mcp-crawl4ai-rag:
    build: .
    container_name: mcp_crawl4ai_rag_ed
    ports:
      - "8051:8051"
    environment:
      TZ: 'America/Sao_Paulo'
      HOST: '0.0.0.0'
      PORT: '8051'
      TRANSPORT: 'sse'
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
    restart: unless-stopped
    volumes:
      - mcp_data:/app/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  mcp_data:
