version: '3.8'

services:
  mcp-crawl4ai-rag:
    build: .
    container_name: mcp_crawl4ai_rag_ed
    ports:
      - "8051:8051"
    environment:
      HOST: '0.0.0.0'
      PORT: '8051'
      TRANSPORT: 'sse'
      OPENAI_API_KEY: 'SUA_OPENAI_API_KEY_AQUI'
      SUPABASE_URL: 'SUA_URL_DO_PROJETO_SUPABASE_AQUI'
      SUPABASE_SERVICE_KEY: 'SUA_SUPABASE_SERVICE_KEY_AQUI'
    restart: unless-stopped
    volumes:
      - mcp_data:/app/data

volumes:
  mcp_data: